<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [6]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

# a named user-defined function

print(greeting("Superman"))

def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()

# your function can essentially return anything, this is defined by the user

list_min, list_max, list_mean = basic_stats([1, 2, 3, 4, 5])

Hello Superman!


### 1.2 Named functions that don’t return

Functions may not require a return statement. An example is print()

Idk I guess I'll find out more later on

### 1.3 Anonymous functions

In [11]:
my_short_function = lambda name: f"Hello {name}!"

print(my_short_function("Super Man"))

Hello Super Man!


In [20]:
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

print(sorted(numbers))                         # Sort by comparing the default key 
                                        # (i.e. the 1st element) 

# the stuff you can add after entering the main argument in a function like sorted() can help to further specify how the
# function is to take the argument and compute it
    
sorted(numbers, key=lambda x: x[1])     # Sort by comparing a custom key
                                        # that uses the 2nd element

sorted(numbers, key=lambda x: sum(x))   # Sort by comparing a custom key
                                        # that uses the sum of the elements

[[0, 9, 19], [1, 8, 18], [2, 7, 17], [3, 6, 16], [4, 5, 15], [5, 4, 14], [6, 3, 13], [7, 2, 12], [8, 1, 11], [9, 0, 10]]


[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

### 1.4 Optional arguments

In [22]:
def greeting(name='no one'):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'
    
greeting()

# A default argument is given directly after the name of the function you are defining. This allows us to make the
# input arugment optional when we call the function

'Hello no one!'

In [31]:
?print 
# (essentially the same as help(print)) !!!

print('I', 'am', 'Batman!')                 # Just for comparison
#> I am Batman!
print('I', 'am', 'Batman!', sep='---')  
#> I---am---Batman!

I am Batman!
I---am---Batman!


## 2 The importance of functions?

### 2.1 An argument for functions

Functional abstraction is pogger

Essentially it is just learning to treat functions as black boxes in which you can input stuff and it will give you your output. By focusing on what it does rather than HOW it does it, it can help you focus more on the logical flow of the problems you are trying to solve rather than getting caught up in the details of how the functions work.

Functional abstraction allows for (1) reusability and (2) maintainability of code.

### 2.2 A word of caution

Don't misuse functions by making them too complicated. I.e. trying to do too much with a function or having a function accept too many arguments. The simpler the better.

## Exercise 1 :  Do you know why?

In [33]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'

greeting('Batman')

'Hello Batman! So, nice to meet you!'

In [34]:
def f(x):
    x += 1
    return x
    x += 1
    print(x)
    
f(3)

4

When functions are defined and called, once it hits a return statement, it will exit from the function and carry out the return statement. In the case of greeting(), if the if conditional is fulfilled, Python will hit the return statement under the if conditional and then exit from the function. However, if it is not fulfilled, Python will carry on looking at the following lines until it hits another return statement.

## Exercise 2 :  Calculator functions

In [52]:
def add(x, y):
    return x+y

def subtract(x, y):
    return x-y

def multiply(x, y):
    return x*y

def divide(x, y):
    if any(y==0): return "Cannot divide by zero"
    return x/y

x=np.array([36, 34, 44, 76, 27])
y=np.array([0, 66, 56, 24, 73])

print(add(x, y))
print(subtract(x, y))
print(multiply(x, y))
print(divide(x, y))

# any() and all() are Python functions where you insert a Boolean operator in the parentheses
# any() will check if any of the conditions listed are True and will return True. all() checks if all of the conditions
# are True and will return True if so, False if not.

[ 36 100 100 100 100]
[ 36 -32 -12  52 -46]
[   0 2244 2464 1824 1971]
Cannot divide by zero


## Exercise 3 :  max_info() with NumPy

In [57]:
def max_info(numbers):
    numbers = np.array(numbers)
    return np.max(numbers), np.argmax(numbers)

numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]

print(max_info(numbers))

(83, 2)
