<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Good)</span></div>

## 1 Check, balances and contingencies

### 1.1 assert

In [3]:
# Syntax of assert:
# [assert condition-to-check, message]

x = 10
assert x >= 0, "x is becoming negative!"

x = -1
assert x >= 0, "x is becoming negative!"

# Programme will run as long as the condition remains True, else it will raise an AssertionError and return the statement
# the user has defined (if the case)

AssertionError: x is becoming negative!

### 1.2 try-except

In [4]:
try:
    number=input("Give me a number and I will calculate its square.")
    square=int(number)**2
    print(f'The square of {number} is {square}!')
except:
    print(f"Oh oh! I cannot square {number}!")

# If any part of the code in the try block causes an error, Python will ignore the error and run the code in the except
# block instead

Give me a number and I will calculate its square.
Oh oh! I cannot square !


## 2 Some loose ends

### 2.1 Positional, keyword and default arguments

In [5]:
def funny_add(a, b, c=1):
    return a + 10*b + 100*c

funny_add(1, 2)           # Two positional, 1 default
#> 121
funny_add(1, 2, 3)        # Three positional
#> 321
funny_add(a=1, b=2)       # Two keyword, 1 default
#> 121
funny_add(c=3, b=1, a=2)  # Three keyword
#> 312
funny_add(1, c=3, b=2)    # One positional, 2 keyword
#> 321
funny_add(1, b=2)         # One positional, 1 keyword, 1 default
#> 121
funny_add(a=2, 1)         # Won't work.
                          # Keywords cannot be followed by 
                          # positional
        
# You can use positional (most common), keyword, or default to pass values to an argument.

SyntaxError: positional argument follows keyword argument (3030867027.py, line 16)

### 2.2 Docstrings

In [6]:
def funny_add(a, b, c=1):
    '''
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.
    '''
    return a + 10*b + 100*c

help(funny_add)

# You can write a body of text directly below a def func() statement as a description of how the function is supposed to
# be used or what the function does.

Help on function funny_add in module __main__:

funny_add(a, b, c=1)
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.



### 2.3 Function are first class citizens

In [7]:
def my_function(angle, trig_function):
        return trig_function(angle)

# Let's use the function
print(my_function(np.pi/2, np.sin))
#> 1.0
print(my_function(np.pi/2, np.cos))
#> 6.123233995736766e-17
print(my_function(np.pi/2, lambda x: np.cos(2*x)))
#> -1.0

# Python is a programming language which supports first-class functions, meaning functions are treated the same way as
# variables. This also allows us to create higher order functions which either take in functions as inputs, return
# functions as outputs or both.
# Remember that when passing functions as arguments into other functions, you cannot have parentheses as this means they
# will not evaluate to functions but to the output of the functions (likely some integer or string or other value)

1.0
6.123233995736766e-17
-1.0


### 2.4 More unpacking

In [8]:
x, y, z = [1, 2, 3]
print(x, y, z)

x, y, z = np.array([1, 2, 3])
print(x, y, z)

x, *y, z = np.array([1, 2, 3, 4, 5])
print(x, y, z)

x, *_, y = [1, 2, 3, 4, 5]
print(x, y)

# * followed by a variable unpacks the whole middle chunk except the ones corresponding to their respective variable
# position (i think)
# *_ will skip the middle chunk

1 2 3
1 2 3
1 [2, 3, 4] 5
1 5


## Exercise 1 :  A better calculator I

In [14]:
def add(x, y):
    return x+y

def subtract(x, y):
    return x-y

def multiply(x, y):
    return x*y

def divide(x, y):
    return x/y
assert all(y != 0), "Cannot divide by zero."

x=np.array([36, 34, 44, 76, 27])
y=np.array([0, 66, 56, 24, 73])
print(divide(x, y))

AssertionError: Cannot divide by zero.

## Exercise 2 :  A better calculator II

In [19]:
def add(x, y):
    try:
        return x+y
    except:
        return "Can't do that"

def subtract(x, y):
    try:
        return x-y
    except:
        return "Can't do that"

def multiply(x, y):
    try:
        return x*y
    except:
        return "Can't do that"
    
def divide(x, y):
    try:
        assert all(y != 0), "Cannot divide by zero."
        return x/y
    except:
        return "Can't do that"

x=np.array([36, 34, 44, 76, 27])
y=np.array([0, 66, 56, 24, 73])

print(add(x, y))
print(subtract(x, y))
print(multiply(x, y))
print(divide(x, y))

[ 36 100 100 100 100]
[ 36 -32 -12  52 -46]
[   0 2244 2464 1824 1971]
Can't do that
