<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

Subsetting means to select a subset within a list or array. Subsetting can consist of indexing, which means to call the index of an element in a list or array, and slicing, which means to select a range of values within the list or array.

In [13]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

x = py_list
y = np_array

# when using slicing indexes, the start value is included in the output while the stop value is not. You can also just
# leave some of the parameters blank if the parameter can be deduced from other parameters given in the slicing index.

print(x[-1:0:-1])                 # Will not include the element with the index 0
print(x[-1:-100000000000:-1])     # Giving Python an index that is out of the list will cause Python to just take
                                  # the first value which is present in the list
print(x[::-1])                    
print(x[11::-2])                  # Python starts counting from the first valid/present element

print(y[::-1])                    # The same thing can be done with NumPy arrays

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2']
['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']
['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']
['j10', 'h8', 'f6', 'd4', 'b2']
['j10' 'i9' 'h8' 'g7' 'f6' 'e5' 'd4' 'c3' 'b2' 'a1']


### 1.2 Subsetting by masking (Arrays only)

In [23]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
# This will set True or False values to each element in the array since the array checks each item in the array with the
# given value and comparison operator

print(my_mask)
print(np_array[np_array > 3])   # This is similar to the filtering i did in storing_data_(need) and is different from
                                # masking because it filters the array according to the given value and comparison
                                # operator.
print(np_array[~(np_array > 3)])                         # '~' means 'NOT'
print(np_array[(np_array > 3) & (np_array < 8)])         # '&' means 'AND'
print(np_array[(np_array < 3) | (np_array > 8)])         # '|' means 'OR'

# These are bitwise operators in NumPy. Remember that they should be placed outside of the argument 
# (array name [comparison operator] [value])

[False False False  True  True  True  True  True  True  True]
[ 4  5  6  7  8  9 10]
[1 2 3]
[4 5 6 7]
[ 1  2  9 10]


### 1.3 Indexing & Slicing 2D Lists

In [30]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

print(py_list_2d[3])        # What is at position 4 (index 3)?
print(py_list_2d[3][0])     # FIRST element at position 4 (index 3) 
print(py_list_2d[:3])       # 
print(py_list_2d[:3][0])    # Does NOT give the first element of each list in index 0, 1, 2. Instead, it gives the first
                            # item in the new list created from slicing consisting of the first 3 elements.
print(py_list_2d[3:6][0])   # Will return [4, "D"]

# When you include a subset after a subset, it will create a new subset based on the previous one.

[4, 'D']
4
[[1, 'A'], [2, 'B'], [3, 'C']]
[1, 'A']
[4, 'D']


### 1.4 Indexing & Slicing 2D Arrays

In [41]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

print(np_array_2d[3])       # What is at position 4 (index 3)? 
print(np_array_2d[3, 0])    # FIRST element at position 4 (index 3)
print(np_array_2d[:3])      # Outputs all elements in the array in index 0, 1 and 2
print(np_array_2d[:3, 0])   # First element of each array in index 0, 1 and 2
print(np_array_2d[3:6, 1])  # Second element of each array in index 3, 4 and 6
print(np_array_2d[:, 0])    # All first elements of all the arrays in the array

['4' 'D']
4
[['1' 'A']
 ['2' 'B']
 ['3' 'C']]
['1' '2' '3']
['D' 'E' 'F']
['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


### 1.5 Growing lists

In [3]:
x=[1]*10
print(x)

x=[1]
x+= [2]
x+= [3]
x+= [4]
print(x)

# appending one digit to the end of the list

x=[1]
x+= [2, 3, 4]
print(x)

# appending a bunch of digits to the list

x=[1]
x= [2, 3, 4] + x
print(x)

# pre-pending multiple items to the list

x=[1]
x.append(2)
x.append(3)
x.append(4)
print(x)

# .append() allows you to automatically add items to the end of any list

x=[1]
#x.append(2, 3, 4)        # Won't work. .append() only takes 1 argument
print(x)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 2, 3, 4]
[1, 2, 3, 4]
[2, 3, 4, 1]
[1, 2, 3, 4]
[1]


## 2 Some loose ends

### 2.1 Tuples

In [24]:
# Tuples make use of parentheses instead of square brackets and is not mutable after being created

a=(1, 2, 3)     # Define tuple
print(a[0])    # Access data (works in the same way as lists)

b = (4, 5 ,6)
c = (3)

# The following will NOT work
# a[0] = -1
# a[0] += [10]    # will produce the TypeError: 'tuple' object does not support item assignment

# a += [4]        
# a += (4)        # TypeError: can only concatenate tuple (not "list") to tuple
a += b
b += (1, 2, 3)
# b += c          # TypeError: can only concatenate tuple (not "list") to tuple

print(a, b)

# Python allows you to grow a tuple by adding other tuples to it, but not integers or lists. So you cannot just add 1 
# integer by itself or a "bracketed" integer thinking it is a tuple lol.

1
(1, 2, 3, 4, 5, 6) (4, 5, 6, 1, 2, 3)


### 2.2 Be VERY careful when copying

In [34]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

# Apparently is the wrong way to "copy" a list because all it does is assigns the same list to the variables y and z.
# So whatever changes made to the list assigned to x will also happen to the variables y and z

x=[1, 2, 3]
y=x.copy()
z=x.copy()

x+=[4, 5, 6]

print(x)
print(y)
print(z)

# You can use .copy() to safely copy over a list to another variable.

tup = (9, 8, 7)
# tup_copy = tup.copy()        # Will raise AttributeError: 'tuple' object has no attribute 'copy'

# The .copy() method is only specific to lists.

[1, 2, 3, 4, 5, 6]
[1, 2, 3]
[1, 2, 3]


## Exercise 1 :  Total recall?

**Subsetting**: Creating a subset of an object (whether string, list, integer, etc)

**Indexing**: Calling a single item in an object using its index (whether a character in a string or integer, an item in a list, etc) 

**Slicing**: Calling a part of the object by defining a start, stop and step index of the object (step parameter is optional) 

**Masking**: Assigning True or False values to items in a NumPy array to "mask" the items in the array according to a specified condition

## Exercise 2 :  Show me the ‘odd’ letters

In [65]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

numbers = np_array_2d[:, 0]   # Creates a new list containing the first item of each array in the lowest dimension
np_array_2d_int = numbers.astype(int)   # Converts the items in the new list into integers
is_odd = np_array_2d_int % 2 == 1
print(is_odd)
print(np_array_2d[is_odd][:, 1])

[ True  True False False  True  True False False False  True]
['A' 'C' 'E' 'G' 'I']
